name: Unstable CI

on: [push]
jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up environment
      run: |
        echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Build mod
      run: make android -j$(nproc)

    - name: Upload desktop jar
      uses: actions/upload-artifact@v4
      with:
        name: Desktop-only build
        path: ExampleJavaMod-Desktop.jar
    - name: Upload universal jar
      uses: actions/upload-artifact@v4
      with:
        name: Android + Desktop build
        path: ExampleJavaMod.jar
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
    - name: Upload release jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ExampleJavaMod.jar
        asset_name: ExampleJavaMod.jar
        asset_content_type: application/zip
