name: Java CI (commit test)

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
        echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build mod
      run: make android -j$(nproc)

    - name: Upload desktop jar
      uses: actions/upload-artifact@v2
      with:
        name: Desktop-only build
        path: ExampleJavaMod-Desktop.jar
    - name: Upload universal jar
      uses: actions/upload-artifact@v2
      with:
        name: Android + Desktop build
        path: ExampleJavaMod.jar
